### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by unbeatable-101** [TheDiscordian/ipfs-sync#44]
```zsh
Last login: Tue Jun  1 12:48:29 on ttys000
williamdavis@Williams-Air ~ % go install github.com/TheDiscordian/ipfs-sync@latest
go: downloading github.com/TheDiscordian/ipfs-sync v0.5.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/sys v0.0.0-20191005200804-aed5e4c7ecf9
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
williamdavis@Williams-Air ~ % brew reinstall libexec
Error: No available formula or cask with the name "libexec".
williamdavis@Williams-Air ~ % ipfs-sync -config $HOME/.ipfs-sync.yaml -db $HOME/.ipfs-sync.db
2021/06/01 13:13:16 ipfs-sync starting up...
2021/06/01 13:13:16 Loading config file /Users/williamdavis/.ipfs-sync.yaml
2021/06/01 13:13:16 Starting up ipfs-sync  ...
2021/06/01 13:13:16 Starting watchdog...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x10110dda8]

goroutine 1 [running]:
main.filePathWalkDir.func1(0x14000152800, 0x1f, 0x0, 0x0, 0x1012188f8, 0x140001175f0, 0x0, 0x169)
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:305 +0x28
path/filepath.WalkDir(0x14000152800, 0x1f, 0x140006a5b40, 0x1011a23e0, 0x16)
	/opt/homebrew/Cellar/go/1.16.4/libexec/src/path/filepath/path.go:463 +0x70
main.filePathWalkDir(0x14000152800, 0x1f, 0x30, 0x140001175c0, 0x14000080480, 0x0, 0x0)
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:304 +0x58
main.HashDir(0x14000152800, 0x1f, 0x101173500, 0x1, 0x0, 0x2)
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/db.go:100 +0x30
main.WatchDog()
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:658 +0x648
main.main()
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:751 +0x108
williamdavis@Williams-Air ~ % go unnstall github.com/TheDiscordian/ipfs-sync@latest
go unnstall: unknown command
Run 'go help' for usage.
williamdavis@Williams-Air ~ % go uninstall github.com/TheDiscordian/ipfs-sync@latest
go uninstall: unknown command
Run 'go help' for usage.
williamdavis@Williams-Air ~ % go help
Go is a tool for managing Go source code.

Usage:

	go <command> [arguments]

The commands are:

	bug         start a bug report
	build       compile packages and dependencies
	clean       remove object files and cached files
	doc         show documentation for package or symbol
	env         print Go environment information
	fix         update packages to use new APIs
	fmt         gofmt (reformat) package sources
	generate    generate Go files by processing source
	get         add dependencies to current module and install them
	install     compile and install packages and dependencies
	list        list packages or modules
	mod         module maintenance
	run         compile and run Go program
	test        test packages
	tool        run specified go tool
	version     print Go version
	vet         report likely mistakes in packages

Use "go help <command>" for more information about a command.

Additional help topics:

	buildconstraint build constraints
	buildmode       build modes
	c               calling between Go and C
	cache           build and test caching
	environment     environment variables
	filetype        file types
	go.mod          the go.mod file
	gopath          GOPATH environment variable
	gopath-get      legacy GOPATH go get
	goproxy         module proxy protocol
	importpath      import path syntax
	modules         modules, module versions, and more
	module-get      module-aware go get
	module-auth     module authentication using go.sum
	packages        package lists and patterns
	private         configuration for downloading non-public code
	testflag        testing flags
	testfunc        testing functions
	vcs             controlling version control with GOVCS

Use "go help <topic>" for more information about that topic.

williamdavis@Williams-Air ~ % go list
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
williamdavis@Williams-Air ~ % cd /Users/williamdavis/go/pkg/mod/github.com/\!the\!discordian/ipfs-sync@v0.5.0
williamdavis@Williams-Air ipfs-sync@v0.5.0 % go list
github.com/TheDiscordian/ipfs-sync
williamdavis@Williams-Air ipfs-sync@v0.5.0 % brew install systemd
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.

systemd: Linux is required for this software.
libcap: Linux is required for this software.
Error: Unsatisfied requirements failed this build.
williamdavis@Williams-Air ipfs-sync@v0.5.0 % brew install systemd -f
systemd: Linux is required for this software.
libcap: Linux is required for this software.
Error: Unsatisfied requirements failed this build.
williamdavis@Williams-Air ipfs-sync@v0.5.0 % cd
williamdavis@Williams-Air ~ % go install github.com/TheDiscordian/ipfs-sync@latest
go: downloading github.com/TheDiscordian/ipfs-sync v0.5.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/sys v0.0.0-20191005200804-aed5e4c7ecf9
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
williamdavis@Williams-Air ~ % ipfs-sync
2021/06/01 13:17:36 ipfs-sync starting up...
2021/06/01 13:17:36 dirs field is required as flag, or in config (ex: {"ID":"UniqueIdentifier", "Dir":"/path/to/dir/to/sync/", "Nocopy": false}).
williamdavis@Williams-Air ~ % ipfs-sync -config $HOME/.ipfs-sync.yaml          
2021/06/01 13:17:46 ipfs-sync starting up...
2021/06/01 13:17:46 Loading config file /Users/williamdavis/.ipfs-sync.yaml
2021/06/01 13:17:47 Starting up ipfs-sync  ...
2021/06/01 13:17:47 Starting watchdog...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x101109da8]

goroutine 1 [running]:
main.filePathWalkDir.func1(0x1400015a800, 0x1f, 0x0, 0x0, 0x1012148f8, 0x140000123c0, 0x0, 0x169)
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:305 +0x28
path/filepath.WalkDir(0x1400015a800, 0x1f, 0x14000165b40, 0x10119e3e0, 0x16)
	/opt/homebrew/Cellar/go/1.16.4/libexec/src/path/filepath/path.go:463 +0x70
main.filePathWalkDir(0x1400015a800, 0x1f, 0x30, 0x14000012390, 0x14000044900, 0x0, 0x0)
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:304 +0x58
main.HashDir(0x1400015a800, 0x1f, 0x10116f500, 0x1, 0x0, 0x2)
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/db.go:100 +0x30
main.WatchDog()
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:658 +0x648
main.main()
	/Users/williamdavis/go/pkg/mod/github.com/!the!discordian/ipfs-sync@v0.5.0/main.go:751 +0x108
williamdavis@Williams-Air ~ % 
```

**Comment by TheDiscordian** [comment]
For some reason `info` is nil, and I guess that's a problem: https://github.com/TheDiscordian/ipfs-sync/blob/5d7cd9c9863b21c85ab87e0fc7422d4d449d5a75/main.go#L305

The fix is to check if it's nil, and return a better error if so. I believe this is caused by it being unable to find the directory being pointed to.

**Comment by unbeatable-101** [comment]
Thanks, that was the problem.

For example I had the directory listed as `~/element` when it should have been just `element`
